//
//  AllTeams.swift
//  Outrank
//
//  Created by Ryan Token on 10/5/21.
//

import Foundation

/// The FBS field, and the one place in the app that team names live.
///
/// Adding or removing a program is a single edit here — the picker list and the
/// API-key lookup are both derived from `all`.
nonisolated enum AllTeams {
    /// Every FBS program, in the order the pickers show them.
    static let all: [FBSTeam] = [
        FBSTeam(name: "Air Force", apiKey: "AirForce"),
        FBSTeam(name: "Akron", apiKey: "Akron"),
        FBSTeam(name: "Alabama", apiKey: "Alabama"),
        FBSTeam(name: "App State", apiKey: "AppState"),
        FBSTeam(name: "Arizona", apiKey: "Arizona"),
        FBSTeam(name: "Arizona St.", apiKey: "ArizonaSt"),
        FBSTeam(name: "Arkansas", apiKey: "Arkansas"),
        FBSTeam(name: "Arkansas St.", apiKey: "ArkansasSt"),
        FBSTeam(name: "Army West Point", apiKey: "ArmyWestPoint"),
        FBSTeam(name: "Auburn", apiKey: "Auburn"),
        FBSTeam(name: "Ball St.", apiKey: "BallSt"),
        FBSTeam(name: "Baylor", apiKey: "Baylor"),
        FBSTeam(name: "Boise St.", apiKey: "BoiseSt"),
        FBSTeam(name: "Boston College", apiKey: "BostonCollege"),
        FBSTeam(name: "Bowling Green", apiKey: "BowlingGreen"),
        FBSTeam(name: "Buffalo", apiKey: "Buffalo"),
        FBSTeam(name: "BYU", apiKey: "BYU"),
        FBSTeam(name: "California", apiKey: "California"),
        FBSTeam(name: "Central Mich.", apiKey: "CentralMich"),
        FBSTeam(name: "Charlotte", apiKey: "Charlotte"),
        FBSTeam(name: "Cincinnati", apiKey: "Cincinnati"),
        FBSTeam(name: "Clemson", apiKey: "Clemson"),
        FBSTeam(name: "Coastal Carolina", apiKey: "CoastalCarolina"),
        FBSTeam(name: "Colorado", apiKey: "Colorado"),
        FBSTeam(name: "Colorado St.", apiKey: "ColoradoSt"),
        FBSTeam(name: "Delaware", apiKey: "Delaware"),
        FBSTeam(name: "Duke", apiKey: "Duke"),
        FBSTeam(name: "East Carolina", apiKey: "EastCarolina"),
        FBSTeam(name: "Eastern Mich.", apiKey: "EasternMich"),
        FBSTeam(name: "FIU", apiKey: "FIU"),
        FBSTeam(name: "Fla. Atlantic", apiKey: "FlaAtlantic"),
        FBSTeam(name: "Florida", apiKey: "Florida"),
        FBSTeam(name: "Florida St.", apiKey: "FloridaSt"),
        FBSTeam(name: "Fresno St.", apiKey: "FresnoSt"),
        FBSTeam(name: "Ga. Southern", apiKey: "GaSouthern"),
        FBSTeam(name: "Georgia", apiKey: "Georgia"),
        FBSTeam(name: "Georgia St.", apiKey: "GeorgiaSt"),
        FBSTeam(name: "Georgia Tech", apiKey: "GeorgiaTech"),
        FBSTeam(name: "Hawaii", apiKey: "Hawaii"),
        FBSTeam(name: "Houston", apiKey: "Houston"),
        FBSTeam(name: "Illinois", apiKey: "Illinois"),
        FBSTeam(name: "Indiana", apiKey: "Indiana"),
        FBSTeam(name: "Iowa", apiKey: "Iowa"),
        FBSTeam(name: "Iowa St.", apiKey: "IowaSt"),
        FBSTeam(name: "Jacksonville St.", apiKey: "JacksonvilleSt"),
        FBSTeam(name: "James Madison", apiKey: "JamesMadison"),
        FBSTeam(name: "Kansas", apiKey: "Kansas"),
        FBSTeam(name: "Kansas St.", apiKey: "KansasSt"),
        FBSTeam(name: "Kennesaw St.", apiKey: "KennesawSt"),
        FBSTeam(name: "Kent St.", apiKey: "KentSt"),
        FBSTeam(name: "Kentucky", apiKey: "Kentucky"),
        FBSTeam(name: "Liberty", apiKey: "Liberty"),
        FBSTeam(name: "Louisiana", apiKey: "Louisiana"),
        FBSTeam(name: "Louisiana Tech", apiKey: "LouisianaTech"),
        FBSTeam(name: "Louisville", apiKey: "Louisville"),
        FBSTeam(name: "LSU", apiKey: "LSU"),
        FBSTeam(name: "Marshall", apiKey: "Marshall"),
        FBSTeam(name: "Maryland", apiKey: "Maryland"),
        FBSTeam(name: "Massachusetts", apiKey: "Massachusetts"),
        FBSTeam(name: "Memphis", apiKey: "Memphis"),
        FBSTeam(name: "Miami (FL)", apiKey: "MiamiFL"),
        FBSTeam(name: "Miami (OH)", apiKey: "MiamiOH"),
        FBSTeam(name: "Michigan", apiKey: "Michigan"),
        FBSTeam(name: "Michigan St.", apiKey: "MichiganSt"),
        FBSTeam(name: "Middle Tenn.", apiKey: "MiddleTenn"),
        FBSTeam(name: "Minnesota", apiKey: "Minnesota"),
        FBSTeam(name: "Mississippi St.", apiKey: "MississippiSt"),
        FBSTeam(name: "Missouri", apiKey: "Missouri"),
        FBSTeam(name: "Missouri St.", apiKey: "MissouriSt"),
        FBSTeam(name: "Navy", apiKey: "Navy"),
        FBSTeam(name: "NC State", apiKey: "NCState"),
        FBSTeam(name: "Nebraska", apiKey: "Nebraska"),
        FBSTeam(name: "Nevada", apiKey: "Nevada"),
        FBSTeam(name: "New Mexico", apiKey: "NewMexico"),
        FBSTeam(name: "New Mexico St.", apiKey: "NewMexicoSt"),
        FBSTeam(name: "North Carolina", apiKey: "NorthCarolina"),
        FBSTeam(name: "North Dakota St.", apiKey: "NorthDakotaSt"),
        FBSTeam(name: "North Texas", apiKey: "NorthTexas"),
        FBSTeam(name: "Northern Ill.", apiKey: "NorthernIll"),
        FBSTeam(name: "Northwestern", apiKey: "Northwestern"),
        FBSTeam(name: "Notre Dame", apiKey: "NotreDame"),
        FBSTeam(name: "Ohio", apiKey: "Ohio"),
        FBSTeam(name: "Ohio St.", apiKey: "OhioSt"),
        FBSTeam(name: "Oklahoma", apiKey: "Oklahoma"),
        FBSTeam(name: "Oklahoma St.", apiKey: "OklahomaSt"),
        FBSTeam(name: "Old Dominion", apiKey: "OldDominion"),
        FBSTeam(name: "Ole Miss", apiKey: "OleMiss"),
        FBSTeam(name: "Oregon", apiKey: "Oregon"),
        FBSTeam(name: "Oregon St.", apiKey: "OregonSt"),
        FBSTeam(name: "Penn St.", apiKey: "PennSt"),
        FBSTeam(name: "Pittsburgh", apiKey: "Pittsburgh"),
        FBSTeam(name: "Purdue", apiKey: "Purdue"),
        FBSTeam(name: "Rice", apiKey: "Rice"),
        FBSTeam(name: "Rutgers", apiKey: "Rutgers"),
        FBSTeam(name: "SMU", apiKey: "SMU"),
        FBSTeam(name: "Sacramento St.", apiKey: "SacramentoSt"),
        FBSTeam(name: "Sam Houston", apiKey: "SamHouston"),
        FBSTeam(name: "San Diego St.", apiKey: "SanDiegoSt"),
        FBSTeam(name: "San Jose St.", apiKey: "SanJoseSt"),
        FBSTeam(name: "South Alabama", apiKey: "SouthAlabama"),
        FBSTeam(name: "South Carolina", apiKey: "SouthCarolina"),
        FBSTeam(name: "South Fla.", apiKey: "SouthFla"),
        FBSTeam(name: "Southern California", apiKey: "SouthernCalifornia"),
        FBSTeam(name: "Southern Miss.", apiKey: "SouthernMiss"),
        FBSTeam(name: "Stanford", apiKey: "Stanford"),
        FBSTeam(name: "Syracuse", apiKey: "Syracuse"),
        FBSTeam(name: "TCU", apiKey: "TCU"),
        FBSTeam(name: "Temple", apiKey: "Temple"),
        FBSTeam(name: "Tennessee", apiKey: "Tennessee"),
        FBSTeam(name: "Texas", apiKey: "Texas"),
        FBSTeam(name: "Texas A&M", apiKey: "TexasAM"),
        FBSTeam(name: "Texas St.", apiKey: "TexasSt"),
        FBSTeam(name: "Texas Tech", apiKey: "TexasTech"),
        FBSTeam(name: "Toledo", apiKey: "Toledo"),
        FBSTeam(name: "Tulane", apiKey: "Tulane"),
        FBSTeam(name: "Tulsa", apiKey: "Tulsa"),
        FBSTeam(name: "Troy", apiKey: "Troy"),
        FBSTeam(name: "UAB", apiKey: "UAB"),
        FBSTeam(name: "UCF", apiKey: "UCF"),
        FBSTeam(name: "UCLA", apiKey: "UCLA"),
        FBSTeam(name: "UConn", apiKey: "UConn"),
        FBSTeam(name: "ULM", apiKey: "ULM"),
        FBSTeam(name: "UNLV", apiKey: "UNLV"),
        FBSTeam(name: "UTEP", apiKey: "UTEP"),
        FBSTeam(name: "UTSA", apiKey: "UTSA"),
        FBSTeam(name: "Utah", apiKey: "Utah"),
        FBSTeam(name: "Utah St.", apiKey: "UtahSt"),
        FBSTeam(name: "Vanderbilt", apiKey: "Vanderbilt"),
        FBSTeam(name: "Virginia", apiKey: "Virginia"),
        FBSTeam(name: "Virginia Tech", apiKey: "VirginiaTech"),
        FBSTeam(name: "Washington", apiKey: "Washington"),
        FBSTeam(name: "Washington St.", apiKey: "WashingtonSt"),
        FBSTeam(name: "Wake Forest", apiKey: "WakeForest"),
        FBSTeam(name: "West Virginia", apiKey: "WestVirginia"),
        FBSTeam(name: "Western Ky.", apiKey: "WesternKy"),
        FBSTeam(name: "Western Mich.", apiKey: "WesternMich"),
        FBSTeam(name: "Wisconsin", apiKey: "Wisconsin"),
        FBSTeam(name: "Wyoming", apiKey: "Wyoming")
    ]

    /// Team names, for pickers and lists.
    static let teams: [String] = all.map(\.name)

    private static let namesByAPIKey: [String: String] = Dictionary(
        all.lazy.map { ($0.apiKey, $0.name) },
        uniquingKeysWith: { first, _ in first }
    )

    /// The display name for an API key. Falls back to a readable form of the key so a
    /// program the backend has added but the app does not know about yet still reads
    /// sensibly instead of showing a run-together identifier.
    static func name(forAPIKey apiKey: String) -> String {
        namesByAPIKey[apiKey] ?? apiKey.camelCaseToWords()
    }
}
