//
//  Stat.swift
//  Outrank
//
//  Created by Ryan Token on 10/20/21.
//

import Foundation

nonisolated struct Stat: Codable, Loopable {
    var AppState: Int
    var WestVirginia: Int
    var MichiganSt: Int
    var Kansas: Int
    var Oklahoma: Int
    var Vanderbilt: Int
    var Indiana: Int
    var WesternMich: Int
    var SouthCarolina: Int
    var LSU: Int
    var GaSouthern: Int
    var Auburn: Int
    var Louisville: Int
    var Hawaii: Int
    var TexasSt: Int
    var NorthernIll: Int
    var Massachusetts: Int
    var ColoradoSt: Int
    var Iowa: Int
    var EasternMich: Int
    var TCU: Int
    var OklahomaSt: Int
    var KentSt: Int
    var Colorado: Int
    var Michigan: Int
    var SouthAlabama: Int
    var BallSt: Int
    var Cincinnati: Int
    var MiamiOH: Int
    var MiamiFL: Int
    var UCLA: Int
    var Purdue: Int
    var PennSt: Int
    var BYU: Int
    var SouthFla: Int
    var UTEP: Int
    var California: Int
    var OhioSt: Int
    var UConn: Int
    var WakeForest: Int
    var Baylor: Int
    var WashingtonSt: Int
    var SanJoseSt: Int
    var EastCarolina: Int
    var Liberty: Int
    var CentralMich: Int
    var FloridaSt: Int
    var TexasTech: Int
    var Illinois: Int
    var Alabama: Int
    var Rice: Int
    var FIU: Int
    var Temple: Int
    var UNLV: Int
    var Ohio: Int
    var NewMexico: Int
    var CoastalCarolina: Int
    var ArizonaSt: Int
    var Kentucky: Int
    var Arizona: Int
    var BowlingGreen: Int
    var Duke: Int
    var BostonCollege: Int
    var Navy: Int
    var NotreDame: Int
    var BoiseSt: Int
    var Tennessee: Int
    var Minnesota: Int
    var Stanford: Int
    var Pittsburgh: Int
    var FlaAtlantic: Int
    var Charlotte: Int
    var Buffalo: Int
    var NewMexicoSt: Int
    var LouisianaTech: Int
    var OregonSt: Int
    var Arkansas: Int
    var Wyoming: Int
    var Missouri: Int
    var GeorgiaTech: Int
    var GeorgiaSt: Int
    var NorthCarolina: Int
    var Utah: Int
    var Tulsa: Int
    var Washington: Int
    var AirForce: Int
    var Nebraska: Int
    var UAB: Int
    var Memphis: Int
    var NCState: Int
    var UTSA: Int
    var IowaSt: Int
    var SMU: Int
    var Texas: Int
    var Akron: Int
    var FresnoSt: Int
    var MississippiSt: Int
    var NorthTexas: Int
    var Wisconsin: Int
    var Northwestern: Int
    var Toledo: Int
    var Tulane: Int
    var SanDiegoSt: Int
    var Rutgers: Int
    var Houston: Int
    var Troy: Int
    var Nevada: Int
    var TexasAM: Int
    var Clemson: Int
    var SouthernMiss: Int
    var VirginiaTech: Int
    var UCF: Int
    var WesternKy: Int
    var Syracuse: Int
    var OldDominion: Int
    var KansasSt: Int
    var ArmyWestPoint: Int
    var Marshall: Int
    var UtahSt: Int
    var Florida: Int
    var Louisiana: Int
    var Oregon: Int
    var OleMiss: Int
    var MiddleTenn: Int
    var ULM: Int
    var ArkansasSt: Int
    var Maryland: Int
    var SouthernCalifornia: Int
    var Georgia: Int
    var Virginia: Int
    var JamesMadison: Int
    var SamHouston: Int
    var JacksonvilleSt: Int
}
